### ISSUE TITLE
No such module Realm

### ISSUE THREAD

**Issue by quantumpotato** [FancyPixel/done-swift#2] opened 2015-06-20 17:27 UTC
I cloned
I pod installed
I opened xcworkspace
Build: No such module Realm

**Comment by andreamazz** [comment] 2015-06-20 17:29
Hi @quantumpotato 
This might be a duplicate of https://github.com/FancyPixel/done-swift/issues/1
Check that solution and let me know.

**Closed as completed** 2015-07-16 07:43 UTC
